version: 3
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      - dependencies:
    directory: "/"
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
      time: "10:00"
    open-pull-requests-limit: 10
